name = "ReinforcementLearningCore"
uuid = "de1b191a-4ae0-4afa-a27b-92d07f46b2d6"
version = "0.15.3"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
CircularArrayBuffers = "9de3a189-e0c0-4e15-ba3b-b14b9fb0aec1"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
ReinforcementLearningBase = "e575027e-6cd6-5018-9292-cdc6200d2b44"
ReinforcementLearningTrajectories = "6486599b-a3cd-4e92-a99a-2cea90cc8c3c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
AbstractTrees = "0.3, 0.4"
Adapt = "3, 4"
ChainRulesCore = "1"
CircularArrayBuffers = "0.1.12"
Crayons = "4"
Distributions = "0.25"
FillArrays = "0.8, 0.9, 0.10, 0.11, 0.12, 0.13, 1"
Flux = "0.14"
GPUArrays = "8, 9, 10"
Metal = "1.0"
ProgressMeter = "1"
Reexport = "1"
ReinforcementLearningBase = "0.13"
ReinforcementLearningTrajectories = "0.4"
Statistics = "1"
StatsBase = "0.32, 0.33, 0.34"
TimerOutputs = "0.5"
UnicodePlots = "1.3, 2, 3"
julia = "1.9"

[extras]
CommonRLInterface = "d842c3ba-07a1-494f-bbec-f5741b0a3e98"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReinforcementLearningEnvironments = "25e41dd2-4622-11e9-1641-f1adca772921"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"

[targets]
test = ["CommonRLInterface", "CUDA", "cuDNN", "DomainSets", "Metal", "Preferences", "ReinforcementLearningEnvironments", "Test", "UUIDs"]
