name = "ReinforcementLearningCore"
uuid = "de1b191a-4ae0-4afa-a27b-92d07f46b2d6"
authors = ["Jun Tian <tianjun.cpp@gmail.com>"]
version = "0.4.6"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReinforcementLearningBase = "e575027e-6cd6-5018-9292-cdc6200d2b44"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
AbstractTrees = "0.3"
Adapt = "2"
BSON = "0.2"
CUDA = "1"
Distributions = "0.22, 0.23, 0.24"
ElasticArrays = "1.2"
FillArrays = "0.8, 0.9"
Flux = "0.11.1"
GPUArrays = "5, 6.0"
ImageTransformations = "0.8"
JLD = "0.10"
MacroTools = "0.5"
ProgressMeter = "1.2"
ReinforcementLearningBase = "0.8.2"
Setfield = "0.6, 0.7"
StatsBase = "0.32, 0.33"
Zygote = "0.5"
julia = "1.4"

[extras]
ReinforcementLearningEnvironments = "25e41dd2-4622-11e9-1641-f1adca772921"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ReinforcementLearningEnvironments"]
