name = "ReinforcementLearningExperiments"
uuid = "6bd458e5-1694-412f-b601-3a888375c491"
authors = ["Jun Tian <tianjun.cpp@gmail.com>"]
version = "0.1.4"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
ReinforcementLearning = "158674fc-8238-5cab-b5ba-03dfc80d1318"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[compat]
Flux = "0.13"
Reexport = "1"
ReinforcementLearning = "0.11"
StableRNGs = "1"
Weave = "0.10"
julia = "1.6"

[extras]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CUDA", "Test"]
