name = "ReinforcementLearning"
uuid = "158674fc-8238-5cab-b5ba-03dfc80d1318"
authors = ["Johanni Brea <jbrea@users.noreply.github.com>", "Jun Tian <tianjun.cpp@gmail.com>"]
version = "0.9.0"

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
ReinforcementLearningBase = "e575027e-6cd6-5018-9292-cdc6200d2b44"
ReinforcementLearningCore = "de1b191a-4ae0-4afa-a27b-92d07f46b2d6"
ReinforcementLearningEnvironments = "25e41dd2-4622-11e9-1641-f1adca772921"
ReinforcementLearningZoo = "d607f57d-ee1e-4ba7-bcf2-7734c1e31854"

[compat]
Reexport = "1"
ReinforcementLearningBase = "0.9"
ReinforcementLearningCore = "0.7"
ReinforcementLearningEnvironments = "0.4, 0.5"
ReinforcementLearningZoo = "0.3"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
