name = "ReinforcementLearningEnvironments"
uuid = "25e41dd2-4622-11e9-1641-f1adca772921"
authors = ["Jun Tian <juti@microsoft.com>"]
version = "0.4.7"

[deps]
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReinforcementLearningBase = "e575027e-6cd6-5018-9292-cdc6200d2b44"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
GR = "0.46, 0.47, 0.48, 0.49, 0.50, 0.51, 0.52, 0.53, 0.54"
IntervalSets = "0.5"
MacroTools = "0.5"
OrdinaryDiffEq = "5"
ReinforcementLearningBase = "0.9.2"
Requires = "1.0"
StatsBase = "0.32, 0.33"
julia = "1.3"
