name = "ReinforcementLearningEnvironments"
uuid = "25e41dd2-4622-11e9-1641-f1adca772921"
version = "0.9.1"

[deps]
CommonRLInterface = "d842c3ba-07a1-494f-bbec-f5741b0a3e98"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReinforcementLearningBase = "e575027e-6cd6-5018-9292-cdc6200d2b44"
ReinforcementLearningCore = "de1b191a-4ae0-4afa-a27b-92d07f46b2d6"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CommonRLInterface = "^0.3.2"
DelimitedFiles = "1"
IntervalSets = "0.7"
MacroTools = "0.5"
OpenSpiel = "0.2.1"
ReinforcementLearningBase = "0.13"
ReinforcementLearningCore = "0.15"
Requires = "1.0"
StatsBase = "0.32, 0.33, 0.34"
julia = "1.6"

[extras]
ArcadeLearningEnvironment = "b7f77d8d-088d-5e02-8ac0-89aab2acc977"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
OpenSpiel = "ceb70bd2-fe3f-44f0-b81f-41608acaf2f2"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[targets]
test = [
    "ArcadeLearningEnvironment",
    "JLD2",
    "Conda",
    "DomainSets",
    "Flux",
    "OpenSpiel",
    "OrdinaryDiffEq",
    "PyCall",
    "StableRNGs",
    "Statistics",
    "Test",
    "TimerOutputs",
]
