name = "ReinforcementLearningDatasets"
uuid = "dd1544ca-2576-438c-a599-ae96278fd687"
authors = ["findmyway", "Mobius1D"]
version = "0.1.0"

[deps]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
PNGFiles = "f57f5aa1-a3ce-4bc8-8ab9-96f992907883"
Pickle = "fbb45041-c46e-462f-888f-7c521cafbc2c"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReinforcementLearningBase = "e575027e-6cd6-5018-9292-cdc6200d2b44"
ReinforcementLearningEnvironments = "25e41dd2-4622-11e9-1641-f1adca772921"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
TFRecord = "841416d8-1a6a-485a-b0fc-1328d0f53d5e"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
CodecZlib = "0.7"
DataDeps = "0.7"
Flux = "0.12"
HDF5 = "0.15"
ImageCore = "0.9"
NPZ = "0.4"
PNGFiles = "0.3"
Pickle = "0.2"
Pipe = "1.3"
ProgressMeter = "1.7"
PyCall = "1.92"
ReinforcementLearningBase = "0.9"
ReinforcementLearningEnvironments = "0.6.3"
Setfield = "0.7"
TFRecord = "0.3"
UnicodePlots = "1.3"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
