name = "ReinforcementLearningZoo"
uuid = "d607f57d-ee1e-4ba7-bcf2-7734c1e31854"
version = "0.5.11"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CircularArrayBuffers = "9de3a189-e0c0-4e15-ba3b-b14b9fb0aec1"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReinforcementLearningBase = "e575027e-6cd6-5018-9292-cdc6200d2b44"
ReinforcementLearningCore = "de1b191a-4ae0-4afa-a27b-92d07f46b2d6"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
AbstractTrees = "0.3"
CUDA = "3"
CircularArrayBuffers = "0.1"
DataStructures = "0.18"
Distributions = "0.24, 0.25"
Flux = "0.12"
IntervalSets = "0.5, 0.7"
MacroTools = "0.5"
ReinforcementLearningBase = "0.9"
ReinforcementLearningCore = "0.8.2"
Setfield = "0.6, 0.7, 0.8"
StatsBase = "0.32, 0.33"
StructArrays = "0.4, 0.5, 0.6"
Zygote = "0.5, 0.6"
julia = "1.6"

[extras]
OpenSpiel = "ceb70bd2-fe3f-44f0-b81f-41608acaf2f2"
ReinforcementLearningEnvironments = "25e41dd2-4622-11e9-1641-f1adca772921"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "OpenSpiel", "ReinforcementLearningEnvironments", "StableRNGs"]
